# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20160308_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='data_sources',
            field=models.ManyToManyField(blank=True, to='events.DataSource'),
        ),
    ]
