# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 01:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_auto_20160308_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='calendar',
        ),
        migrations.AddField(
            model_name='calendar',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='data_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.DataSource'),
            preserve_default=False,
        ),
    ]
