# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20160309_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='url',
        ),
    ]
