# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_datasource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='url',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
