# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-21 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_datasource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='header_first',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
