# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-30 21:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils import timezone
from pytz import UTC


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_datasource_header_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.make_aware(datetime.datetime(2016, 3, 30, 21, 51, 52, 77231), UTC)),
            preserve_default=False,
        ),
    ]
