# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-05 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='uid',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
